# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
