# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20160219_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author_id',
        ),
    ]
