# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0005_remove_question_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
